### ISSUE TITLE
Containerize the binary

### ISSUE THREAD

**Issue by debloper** [satran/dohproxy#2]
Easier to use, removing the language specific toolchain/runtime/environment setup (i.e. golang in this case).

**Comment by debloper** [comment]
Nah... a much simpler way would be to [release](https://help.github.com/articles/creating-releases/) a standalone executable(s). This doesn't need any other runtime deps anyway.

**Comment by satran** [comment]
Making it to a docker container helped me solve the chicken egg problem of resolving the HTTP server and running this standalone. I have pushed my build in `satran/dohproxy`.  I have also added a few comments to run it using docker: https://github.com/satran/dohproxy#running-it-as-a-docker-container
