### ISSUE TITLE
Please also use `[::1]`

### ISSUE THREAD

**Issue by kseistrup** [satran/dohproxy#3]
Currently `dohproxy` only listens on `127.0.0.1:5353`. Could we have it use `[::1]:5353` as well?

**Comment by satran** [comment]
The `host` flag allows you to do so. If you provide `-host ""` it listens on all interfaces. I know it's a bit quirky, but I'm open to PRs ;)

**Comment by kseistrup** [comment]
I don't speak golang, but what happens if you substitute `localhost:5353` for `127.0.0.1:5353`?

**Comment by satran** [comment]
I'm not sure I understood your comment. If you run the command using `dohproxy -host ""` it will serve on all interfaces. This means it will serve on localhost and 127.0.0.1.

**Comment by kseistrup** [comment]
It should certainly _not_ listen on all interfaces. Listening on `::` / `0.0.0.0` makes it available from everywhere, which is not what we want.

I was suggesting that `localhost` be the default hardcoded host instead of `127.0.0.1` in the hope that the OS would choose a sensible value for `localhost` according to `/etc/gai.conf` (i.e., `::1` if it exists, else `127.0.0.1`).

**Comment by satran** [comment]
You are correct. What you suggested works, thanks. I have updated it in the commit attached with this PR.
